(function(){
'use strict';
const recipes=Array.isArray(window.ARK_CRAFTING_RECIPES)?window.ARK_CRAFTING_RECIPES:[];

const EXACT={
'Rex Saddle':'Sela de Rex','Argentavis Saddle':'Sela de Argentavis','Ankylo Saddle':'Sela de Anquilossauro','Pteranodon Saddle':'Sela de Pteranodonte','Therizinosaurus Saddle':'Sela de Therizinossauro','Crossbow':'Besta','Longneck Rifle':'Rifle de Cano Longo','Assault Rifle':'Rifle de Assalto','Fabricator':'Fabricador','Smithy':'Ferraria','Mortar and Pestle':'Pilão','Refining Forge':'Forja de Refino','Chemistry Bench':'Bancada de Química','Industrial Forge':'Forja Industrial','Industrial Grill':'Grelha Industrial','Industrial Cooker':'Panela Industrial','Industrial Grinder':'Moedor Industrial','Tek Replicator':'Replicador Tek',
'Advanced Bullet':'Munição Avançada','Advanced Rifle Bullet':'Munição Avançada de Rifle','Advanced Sniper Bullet':'Munição Avançada de Rifle de Precisão','Simple Bullet':'Munição Simples','Simple Rifle Ammo':'Munição Simples de Rifle','Simple Shotgun Ammo':'Munição Simples de Escopeta','Stone Arrow':'Flecha de Pedra','Tranq Arrow':'Flecha Tranquilizante','Tranquilizer Dart':'Dardo Tranquilizante','Shocking Tranquilizer Dart':'Dardo Tranquilizante Eletrizante','Metal Arrow':'Flecha de Metal','Flame Arrow':'Flecha Flamejante','Grappling Hook':'Gancho de Escalada','Rocket Propelled Grenade':'Granada Propelida por Foguete','Cannon Ball':'Bala de Canhão','Cannon Shell':'Projétil de Canhão','Chain Bola':'Bola de Corrente','Spear Bolt':'Virote de Lança','Tranq Spear Bolt':'Virote Tranquilizante','C4 Charge':'Carga de C4','Flamethrower Ammo':'Munição de Lança-chamas','Net Projectile':'Projétil de Rede','Zip-Line Anchor':'Âncora de Tirolesa','Transponder Node':'Nó Transponder',
'Campfire':'Fogueira','Cooking Pot':'Panela','Preserving Bin':'Caixa de Conservação','Refrigerator':'Geladeira','Air Conditioner':'Ar-Condicionado','Electrical Generator':'Gerador Elétrico','Electrical Outlet':'Tomada Elétrica','Feeding Trough':'Comedouro','Cryofridge':'Criogeladeira','Egg Incubator':'Incubadora de Ovos','Compost Bin':'Caixa de Compostagem','Beer Barrel':'Barril de Cerveja','Bookshelf':'Estante','Vault':'Cofre','Large Storage Box':'Caixa Grande de Armazenamento','Storage Box':'Caixa de Armazenamento','Simple Bed':'Cama Simples','Bunk Bed':'Beliche','Hide Sleeping Bag':'Saco de Dormir de Couro','Standing Torch':'Tocha de Pé','Wall Torch':'Tocha de Parede','Training Dummy':'Boneco de Treino','Auto Turret':'Torreta Automática','Heavy Auto Turret':'Torreta Automática Pesada','Rocket Turret':'Torreta de Foguetes','Ballista Turret':'Torreta de Balista','Catapult Turret':'Torreta de Catapulta','Cannon':'Canhão','Oil Pump':'Bomba de Óleo','Tree Sap Tap':'Torneira de Seiva','Water Well':'Poço de Água','Water Reservoir':'Reservatório de Água','Metal Water Reservoir':'Reservatório de Água de Metal','Wind Turbine':'Turbina Eólica','Toilet':'Vaso Sanitário','Painting Canvas':'Tela de Pintura','War Map':'Mapa de Guerra','Wardrums':'Tambores de Guerra','Mirror':'Espelho','Gravestone':'Lápide','Artifact Pedestal':'Pedestal de Artefato',
'Wooden Raft':'Balsa de Madeira','Motorboat':'Barco a Motor','Canoe':'Canoa','Fish Basket':'Cesto de Peixe','Large Bear Trap':'Armadilha Grande para Ursos','Bear Trap':'Armadilha para Ursos','Dino Leash':'Coleira para Dinossauro','Remote Keypad':'Teclado Remoto','Pressure Plate':'Placa de Pressão','Gas Collector':'Coletor de Gás',
'Electronics':'Eletrônicos','Cementing Paste':'Pasta de Cimento','Achatina Paste':'Pasta de Achatina','Charcoal':'Carvão','Chitin':'Quitina','Clay':'Argila','Element':'Elemento','Element Dust':'Pó de Elemento','Element Shard':'Fragmento de Elemento','Flint':'Sílex','Gasoline':'Gasolina','Gunpowder':'Pólvora','Metal Ingot':'Metal Fundido','Oil':'Óleo','Polymer':'Polímero','Propellant':'Propelente','Sparkpowder':'Pólvora Faiscante','Thatch':'Palha','Absorbent Substrate':'Substrato Absorvente','Charge Battery':'Bateria de Carga','Congealed Gas Ball':'Bola de Gás Congelado','Preserving Salt':'Sal de Conservação','Resin':'Resina','Scrap Metal Ingot':'Lingote de Sucata','Unstable Element':'Elemento Instável','Unstable Element Shard':'Fragmento de Elemento Instável',
'Cloth Boots':'Botas de Tecido','Cloth Gloves':'Luvas de Tecido','Cloth Hat':'Chapéu de Tecido','Cloth Pants':'Calças de Tecido','Cloth Shirt':'Camisa de Tecido','Hide Boots':'Botas de Couro','Hide Gloves':'Luvas de Couro','Hide Hat':'Chapéu de Couro','Hide Pants':'Calças de Couro','Hide Shirt':'Camisa de Couro','Chitin Boots':'Botas de Quitina','Chitin Chestpiece':'Peitoral de Quitina','Chitin Gauntlets':'Manoplas de Quitina','Chitin Helmet':'Capacete de Quitina','Chitin Leggings':'Calças de Quitina','Flak Boots':'Botas de Metal','Flak Chestpiece':'Peitoral de Metal','Flak Gauntlets':'Manoplas de Metal','Flak Helmet':'Capacete de Metal','Flak Leggings':'Calças de Metal','Fur Boots':'Botas de Pele','Fur Cap':'Gorro de Pele','Fur Chestpiece':'Peitoral de Pele','Fur Gauntlets':'Manoplas de Pele','Fur Leggings':'Calças de Pele','Ghillie Boots':'Botas Ghillie','Ghillie Chestpiece':'Peitoral Ghillie','Ghillie Gauntlets':'Manoplas Ghillie','Ghillie Leggings':'Calças Ghillie','Ghillie Mask':'Máscara Ghillie','Gas Mask':'Máscara de Gás','Riot Boots':'Botas Antimotim','Riot Chestpiece':'Peitoral Antimotim','Riot Gauntlets':'Manoplas Antimotim','Riot Helmet':'Capacete Antimotim','Riot Leggings':'Calças Antimotim','Riot Shield':'Escudo Antimotim','Metal Shield':'Escudo de Metal','Wooden Shield':'Escudo de Madeira','SCUBA Flippers':'Nadadeiras de Mergulho','SCUBA Leggings':'Calças de Mergulho','SCUBA Mask':'Máscara de Mergulho','SCUBA Tank':'Cilindro de Mergulho','Night Vision Goggles':'Óculos de Visão Noturna','Heavy Miner\'s Helmet':'Capacete Pesado de Mineiro',
'Tek Boots':'Botas Tek','Tek Chestpiece':'Peitoral Tek','Tek Gauntlets':'Manoplas Tek','Tek Helmet':'Capacete Tek','Tek Leggings':'Calças Tek','Tek Shield':'Escudo Tek','Tek Shoulder Cannon':'Canhão de Ombro Tek','Tek Generator':'Gerador Tek','Tek Teleporter':'Teletransportador Tek','Tek Transmitter':'Transmissor Tek','Tek Trough':'Comedouro Tek','Tek Turret':'Torreta Tek','Tek Light':'Luz Tek','Tek Sensor':'Sensor Tek','Tek Forcefield':'Campo de Força Tek','Tek Dedicated Storage':'Armazenamento Dedicado Tek','Tek Remote Camera':'Câmera Remota Tek','Tek Surveillance Console':'Console de Vigilância Tek','Tek Sleeping Pod':'Cápsula de Dormir Tek','Tek Crop Plot':'Canteiro Tek','Tek Jump Pad':'Plataforma de Salto Tek','Cloning Chamber':'Câmara de Clonagem'
};

const WORDS=[
[/\bSaddle\b/gi,'Sela'],[/\bPlatform\b/gi,'Plataforma'],[/\bTek\b/g,'Tek'],[/\bWooden\b/gi,'de Madeira'],[/\bWood\b/gi,'Madeira'],[/\bStone\b/gi,'Pedra'],[/\bMetal\b/gi,'Metal'],[/\bThatch\b/gi,'Palha'],[/\bAdobe\b/gi,'Adobe'],[/\bGreenhouse\b/gi,'Estufa'],[/\bCeiling\b/gi,'Teto'],[/\bFoundation\b/gi,'Fundação'],[/\bWall\b/gi,'Parede'],[/\bDoorframe\b/gi,'Batente'],[/\bDouble Doorframe\b/gi,'Batente Duplo'],[/\bDouble Door\b/gi,'Porta Dupla'],[/\bDoor\b/gi,'Porta'],[/\bWindowframe\b/gi,'Moldura de Janela'],[/\bWindow\b/gi,'Janela'],[/\bTriangle\b/gi,'Triangular'],[/\bRoof\b/gi,'Telhado'],[/\bStairs\b/gi,'Escadas'],[/\bStaircase\b/gi,'Escadaria'],[/\bRamp\b/gi,'Rampa'],[/\bPillar\b/gi,'Pilar'],[/\bRailing\b/gi,'Corrimão'],[/\bFence Foundation\b/gi,'Fundação de Cerca'],[/\bFence Support\b/gi,'Suporte de Cerca'],[/\bHatchframe\b/gi,'Moldura de Alçapão'],[/\bTrapdoor\b/gi,'Alçapão'],[/\bLadder\b/gi,'Escada'],[/\bDinosaur Gateway\b/gi,'Portal para Dinossauro'],[/\bDinosaur Gate\b/gi,'Portão para Dinossauro'],[/\bGateway\b/gi,'Portal'],[/\bGate\b/gi,'Portão'],[/\bLarge\b/gi,'Grande'],[/\bSmall\b/gi,'Pequeno'],[/\bMedium\b/gi,'Médio'],[/\bGiant\b/gi,'Gigante'],[/\bBehemoth\b/gi,'Behemoth'],
[/\bHelmet\b/gi,'Capacete'],[/\bHat\b/gi,'Chapéu'],[/\bBoots\b/gi,'Botas'],[/\bGloves\b/gi,'Luvas'],[/\bGauntlets\b/gi,'Manoplas'],[/\bChestpiece\b/gi,'Peitoral'],[/\bShirt\b/gi,'Camisa'],[/\bPants\b/gi,'Calças'],[/\bLeggings\b/gi,'Calças'],[/\bShield\b/gi,'Escudo'],[/\bArmor\b/gi,'Armadura'],[/\bSuit\b/gi,'Traje'],[/\bMask\b/gi,'Máscara'],
[/\bRifle\b/gi,'Rifle'],[/\bShotgun\b/gi,'Escopeta'],[/\bPistol\b/gi,'Pistola'],[/\bBow\b/gi,'Arco'],[/\bSword\b/gi,'Espada'],[/\bSpear\b/gi,'Lança'],[/\bPick\b/gi,'Picareta'],[/\bHatchet\b/gi,'Machado'],[/\bTorch\b/gi,'Tocha'],[/\bGrenade\b/gi,'Granada'],[/\bAmmo\b/gi,'Munição'],[/\bBullet\b/gi,'Munição'],[/\bArrow\b/gi,'Flecha'],[/\bDart\b/gi,'Dardo'],[/\bAttachment\b/gi,'Acessório'],
[/\bWater\b/gi,'Água'],[/\bOil\b/gi,'Óleo'],[/\bCrystal\b/gi,'Cristal'],[/\bFiber\b/gi,'Fibra'],[/\bHide\b/gi,'Couro'],[/\bChitin\b/gi,'Quitina'],[/\bKeratin\b/gi,'Queratina'],[/\bPolymer\b/gi,'Polímero'],[/\bElement\b/gi,'Elemento'],[/\bBlack Pearl\b/gi,'Pérola Negra'],[/\bSilica Pearl\b/gi,'Pérola de Sílica'],[/\bCementing Paste\b/gi,'Pasta de Cimento'],[/\bOrganic Polymer\b/gi,'Polímero Orgânico'],[/\bGunpowder\b/gi,'Pólvora'],[/\bSparkpowder\b/gi,'Pólvora Faiscante'],[/\bCharcoal\b/gi,'Carvão'],[/\bNarcotic\b/gi,'Narcótico'],[/\bStimulant\b/gi,'Estimulante'],[/\bRaw Meat\b/gi,'Carne Crua'],[/\bCooked Meat\b/gi,'Carne Cozida'],[/\bPrime Meat\b/gi,'Carne Nobre'],[/\bSpoiled Meat\b/gi,'Carne Podre'],[/\bSap\b/gi,'Seiva'],[/\bClay\b/gi,'Argila'],[/\bSand\b/gi,'Areia'],[/\bSulfur\b/gi,'Enxofre'],[/\bPropellant\b/gi,'Propelente'],[/\bGasoline\b/gi,'Gasolina'],[/\bElectronics\b/gi,'Eletrônicos'],[/\bObsidian\b/gi,'Obsidiana'],[/\bPelt\b/gi,'Pelo'],[/\bWool\b/gi,'Lã'],
[/\bFlag\b/gi,'Bandeira'],[/\bSkin\b/gi,'Visual'],[/\bCostume\b/gi,'Fantasia'],[/\bColoring\b/gi,'Corante'],[/\bBench\b/gi,'Bancada'],[/\bTable\b/gi,'Mesa'],[/\bChair\b/gi,'Cadeira'],[/\bBed\b/gi,'Cama'],[/\bStorage\b/gi,'Armazenamento'],[/\bBox\b/gi,'Caixa'],[/\bGenerator\b/gi,'Gerador'],[/\bCable\b/gi,'Cabo'],[/\bPipe\b/gi,'Cano'],[/\bFlexible\b/gi,'Flexível'],[/\bStraight\b/gi,'Reto'],[/\bVertical\b/gi,'Vertical'],[/\bInclined\b/gi,'Inclinado'],[/\bIntersection\b/gi,'Interseção'],[/\bIntake\b/gi,'Entrada'],[/\bTap\b/gi,'Torneira'],[/\bCrop Plot\b/gi,'Canteiro'],[/\bElevator\b/gi,'Elevador'],[/\bTrack\b/gi,'Trilho'],[/\bTree\b/gi,'Árvore'],[/\bOcean\b/gi,'Oceânica'],[/\bCliff\b/gi,'Penhasco'],[/\bTurret\b/gi,'Torreta']
];

const ING={
'Water':'Água','Giant Bee Honey':'Mel de Abelha Gigante','Rare Mushroom':'Cogumelo Raro','Rare Flower':'Flor Rara','Prime Meat Jerky':'Carne Nobre Seca','Cooked Prime Meat':'Carne Nobre Cozida','Cooked Meat':'Carne Cozida','Organic Polymer':'Polímero Orgânico','Pelt, Hair, or Wool':'Pelo, Cabelo ou Lã','Blue Gem':'Gema Azul','Green Gem':'Gema Verde','Red Gem':'Gema Vermelha','Cactus Sap':'Seiva de Cacto','Element Dust':'Pó de Elemento','Element Ore':'Minério de Elemento','Shell Fragment':'Fragmento de Casco','Raw Salt':'Sal Bruto','Silk':'Seda','Bio Toxin':'Biotoxina','Ammonite Bile':'Bile de Amonite','Dinosaur Egg':'Ovo de Dinossauro','Stone Arrow':'Flecha de Pedra','Simple Bullet':'Munição Simples','Simple Rifle Ammo':'Munição Simples de Rifle','Tranquilizer Dart':'Dardo Tranquilizante','Spear Bolt':'Virote de Lança','Powered On Station':'Estação Ligada','Condensed Gas':'Gás Condensado','Gasbags bladder':'Bexiga de Gasbags','Cactus Sap':'Seiva de Cacto','Fungal Wood':'Madeira Fúngica','Madeira Fúngica':'Madeira Fúngica','Wishbone':'Osso da Sorte','Mistletoe':'Visco','Coal':'Carvão','Cake Slice':'Fatia de Bolo','Red Crystalized Sap':'Seiva Vermelha Cristalizada'
};

function clean(s){return String(s||'').replace(/\s{2,}/g,' ').replace(/\s+-\s+/g,' - ').trim();}
function translateName(name){
  if(EXACT[name]) return EXACT[name];
  let out=String(name||'');
  for(const [re,to] of WORDS) out=out.replace(re,to);
  out=clean(out)
    .replace(/^Sela (.+)$/i,'Sela de $1')
    .replace(/^(.+) Sela$/i,'Sela de $1')
    .replace(/^de Madeira (.+)$/i,'$1 de Madeira')
    .replace(/^Pedra (.+)$/i,'$1 de Pedra')
    .replace(/^Metal (.+)$/i,'$1 de Metal')
    .replace(/^Palha (.+)$/i,'$1 de Palha')
    .replace(/^Adobe (.+)$/i,'$1 de Adobe')
    .replace(/^Estufa (.+)$/i,'$1 de Estufa');
  return out;
}
function translateIngredient(name){return ING[name]||EXACT[name]||translateName(name);}
function translateStation(s){return String(s||'').replace(/Tek Replicator/gi,'Replicador Tek').replace(/Smithy/gi,'Ferraria').replace(/Fabricator/gi,'Fabricador').replace(/Inventory/gi,'Inventário').replace(/Obelisk/gi,'Obelisco').replace(/terminal/gi,'terminal');}

for(const r of recipes){
  const sourceName=r.original||r.nome||'';
  r.original=sourceName;
  r.nome=translateName(sourceName);
  r.estacao=translateStation(r.estacao);
  if(Array.isArray(r.ingredientes)) r.ingredientes=r.ingredientes.map(([n,q])=>[translateIngredient(n),q]);
}
window.ARK_PTBR={translateName,translateIngredient};
})();
