const METODOS={
  Nocaute:'Nocaute',Passivo:'Passivo',Especial:'Especial',Ovo:'Ovo',Filhote:'Filhote'
};
function c(nome,original,metodo,comida,categoria,dica='',variante='Normal'){
  let como='';
  if(metodo==='Nocaute') como=`Use uma armadilha ou terreno seguro, aplique torpor com flechas/dardos tranquilizantes e, quando a criatura apagar, coloque ${comida} no inventário dela. Acompanhe o torpor e use narcótico/biotoxina se necessário.`;
  if(metodo==='Passivo') como=`Não derrube a criatura. Coloque ${comida} no último espaço da barra rápida e aproxime-se com cuidado para alimentar quando aparecer a interação. Aguarde o intervalo entre as alimentações e repita até completar a domesticação.`;
  if(metodo==='Ovo') como=`O adulto selvagem não é domesticado diretamente. Localize um ninho, roube um ovo fertilizado, leve-o para um local seguro, incube na temperatura correta e crie o filhote até a fase adulta.`;
  if(metodo==='Filhote') como=`A domesticação é feita por interação com filhote selvagem. Controle ou distraia os adultos da área e cumpra as interações exigidas pelo filhote até a barra chegar a 100%.`;
  if(metodo==='Especial') como=`Esta criatura usa uma mecânica própria de domesticação; tranquilizantes comuns não são o método principal. Siga a sequência indicada na dica abaixo.`;
  return {nome,original,metodo,comida,categoria,dica,como,variante,id:(variante+'-'+original).toLowerCase().replace(/[^a-z0-9]+/g,'-')};
}

const creatures=[
 c('Achatina','Achatina','Passivo','Bolo de Vegetais Doce','Terrestre','Use armadura ghillie/repelente se a área estiver perigosa.'),
 c('Acrocanthosaurus','Acrocanthosaurus','Nocaute','Ração Excepcional ou carne nobre','Terrestre','É grande e agressivo; uma armadilha resistente evita perseguições longas.'),
 c('Alossauro','Allosaurus','Nocaute','Ração Superior ou carne','Terrestre','Isole do bando antes de derrubar; o bônus de matilha deixa o grupo bem mais perigoso.'),
 c('Peixe-pescador','Anglerfish','Nocaute','Ração Superior ou carne de peixe','Aquático','Leve uma montaria aquática resistente e não deixe o alvo fugir para áreas profundas.'),
 c('Anquilossauro','Ankylosaurus','Nocaute','Ração Regular ou vegetais','Terrestre','Atire no corpo e mantenha distância da cauda.'),
 c('Araneo','Araneo','Passivo','Carne estragada','Caverna','Use Repelente de Insetos e aproxime-se sem provocar outras criaturas da caverna.'),
 c('Archaeopteryx','Archaeopteryx','Nocaute','Quitina','Voador','Tem pouca vida: use arma fraca para não matar antes do nocaute.'),
 c('Archelon','Archelon','Especial','Alimento específico da domesticação','Aquático','A domesticação envolve sua mecânica própria no mar; prepare uma montaria aquática e elimine ameaças próximas antes de iniciar.'),
 c('Argentavis','Argentavis','Nocaute','Ração Superior ou carne nobre','Voador','Uma armadilha com portões para dinossauro torna o processo muito mais seguro.'),
 c('Armadoggo','Armadoggo','Especial','Itens exigidos pela interação','Terrestre','Siga as interações próprias do Armadoggo; ele não é um nocaute convencional.'),
 c('Arthropluera','Arthropluera','Passivo','Caldo de Iluminação / comida preferida','Caverna','Use Repelente de Insetos e aproxime-se com muito cuidado; dano recebido pode interromper a tentativa.'),
 c('Drakeling do Outono','Autumn Drakeling','Especial','Ração Excepcional','Voador','Segure uma tocha, deixe o Drakeling interagir e cumpra a tarefa pedida, como colher, fabricar ou matar; depois alimente e repita.'),
 c('Baryonyx','Baryonyx','Nocaute','Ração Regular ou carne de peixe','Terrestre','Prefira derrubá-lo em terra; na água o ataque de giro pode atordoar sua montaria.'),
 c('Basilossauro','Basilosaurus','Passivo','Ração Excepcional ou carne','Aquático','Elimine as mantas que costumam acompanhá-lo e então faça as alimentações passivas.'),
 c('Beelzebufo','Beelzebufo','Nocaute','Ração Regular ou carne','Terrestre','Cuidado com o torpor causado pelos ataques dele.'),
 c('Bisão','Bison','Nocaute','Ração Superior ou vegetais','Terrestre','Isole um indivíduo do rebanho. Armadilha grande ajuda muito; prefira atirar no corpo.'),
 c('Boaratos','Boaratos','Nocaute','Ração Extraordinária','Astraeos','O torpor cai muito rápido. Leve bastante narcótico ou biotoxina e não se afaste durante o tame.'),
 c('Brontossauro','Brontosaurus','Nocaute','Ração Excepcional ou vegetais','Terrestre','Mantenha distância da cauda e tenha munição suficiente para o alto torpor.'),
 c('Bulbdog','Bulbdog','Passivo','Cogumelo Aquático / alimento preferido','Aberração','Coloque o alimento na barra rápida e alimente; é um pet de luz muito útil em áreas de Aberração.'),
 c('Burrowbuck','Burrowbuck','Passivo','Ração Superior ou cenoura','Terrestre','Use ghillie e, se possível, Caldo de Cacto. Ele se assusta e pode se enterrar e reaparecer em outro ponto.'),
 c('Carbonemys','Carbonemys','Nocaute','Ração Regular ou vegetais','Terrestre','É lenta; caminhe para trás enquanto aplica torpor.'),
 c('Carcharodontosaurus','Carcharodontosaurus','Especial','Cadáveres grandes','Terrestre','Mate criaturas e arraste os cadáveres até ele para ganhar confiança. Quando puder montar, mate criaturas enquanto estiver montado para completar a barra.'),
 c('Carnotauro','Carnotaurus','Nocaute','Ração Regular ou carne','Terrestre','Uma armadilha simples ou terreno alto costuma bastar.'),
 c('Castoroides','Castoroides','Nocaute','Ração Superior ou vegetais','Terrestre','Afaste-o das barragens e dos outros castores antes de começar, porque o grupo fica agressivo.'),
 c('Gato','Cat','Especial','Interação própria','Terrestre','Use a mecânica de aproximação/interação do gato; não trate como nocaute comum.'),
 c('Ceratosaurus','Ceratosaurus','Especial','Hemogoblin Cocktail','Terrestre','Use Hemogoblin Cocktail na criatura que servirá de alvo e faça o Ceratosaurus atacar até entrar no estado correto; depois siga a alimentação especial.'),
 c('Chalicotherium','Chalicotherium','Passivo','Jarra de Cerveja','Terrestre','Coloque a cerveja no último espaço e aproxime sem provocar. Afaste-se depois de cada alimentação.'),
 c('Concavenator','Concavenator','Especial','Não usa comida no início','Terrestre','Encontre-o enterrado na areia, detone um explosivo perto para atordoá-lo, monte rapidamente e complete o minijogo de comandos no ar. Repita até 100%.'),
 c('Cosmo','Cosmo','Especial','Interação própria','Aberração','Siga a mecânica de domesticação do Cosmo; tranquilizantes não são o método principal.'),
 c('Daeodon','Daeodon','Nocaute','Ração Superior ou carne','Terrestre','Leve muita comida: o consumo durante a domesticação é alto.'),
 c('Deinosuchus','Deinosuchus','Passivo','Ração Superior ou carne','Terrestre','Espere ele abrir a boca e use a janela de interação para alimentar; saia da frente antes que volte a atacar.'),
 c('Deinotherium','Deinotherium','Especial','Alimento da interação','Terrestre','A domesticação depende da hierarquia do grupo/líder. Observe o rebanho e faça as interações sem iniciar combate desnecessário.'),
 c('Desmodus','Desmodus','Especial','Bolsas de Sangue','Voador','Carregue várias Bolsas de Sangue e permita que ele agarre você. Ele consumirá as bolsas e aumentará a domesticação.'),
 c('Dilofossauro','Dilophosaur','Nocaute','Ração Básica ou carne','Terrestre','Pouco torpor; uma bola pode facilitar.'),
 c('Dimetrodon','Dimetrodon','Nocaute','Ração Regular ou carne','Terrestre','O torpor pode cair depressa; monitore enquanto alimenta.'),
 c('Dimorfodonte','Dimorphodon','Nocaute','Carne de carneiro ou carne','Voador','Tem pouca vida. Use arma de baixo dano ou dardo para não matá-lo.'),
 c('Diplocaulus','Diplocaulus','Nocaute','Ração Simples ou carne','Aquático','Limpe predadores próximos antes de começar, pois ele é frágil.'),
 c('Diplodoco','Diplodocus','Passivo','Ração Regular ou vegetais','Terrestre','Alimente passivamente. Ele costuma empurrar em vez de causar dano direto.'),
 c('Urso Gigante','Dire Bear','Nocaute','Ração Superior ou mel','Terrestre','Uma armadilha evita a corrida extremamente rápida dele.'),
 c('Lobo Gigante','Direwolf','Nocaute','Ração Superior ou carne','Terrestre','Isole do bando antes do nocaute.'),
 c('Dodô','Dodo','Nocaute','Ração Básica ou frutas','Terrestre','Pouquíssimo torpor; evite arma forte.'),
 c('Doedicurus','Doedicurus','Nocaute','Ração Regular ou vegetais','Terrestre','Evite deixá-lo enrolar; quando ele se fecha, recebe bem menos dano.'),
 c('Dreadmare','Dreadmare','Especial','Mecânica própria','Terrestre','Siga a sequência especial do Dreadmare; não é tame de nocaute convencional.'),
 c('Dreadnoughtus','Dreadnoughtus','Especial','Mecânica própria','Terrestre','É uma domesticação avançada e própria da criatura. Prepare recursos e uma área segura antes de iniciar.'),
 c('Besouro de Esterco','Dung Beetle','Passivo','Fezes','Caverna','Use repelente e coloque fezes no último espaço da barra rápida.'),
 c('Dunkleosteus','Dunkleosteus','Nocaute','Ração Superior ou carne','Aquático','Use montaria aquática resistente e aplique torpor mantendo distância.'),
 c('Elderclaw','Elderclaw','Especial','Semente / recursos de crescimento','Astraeos','Obtenha a semente após enfrentar um Elderclaw, plante em canteiro grande e cuide da planta. Durante o crescimento, entregue os recursos pedidos até gerar a criatura.'),
 c('Enguia Elétrica','Electrophorus','Passivo','Biotoxina','Aquático','Alimente passivamente; vá preparado para os choques e mantenha sua montaria por perto.'),
 c('Equus','Equus','Passivo','Cenoura','Terrestre','Alimente, monte e pressione a interação novamente sempre que ele tentar derrubar você.'),
 c('Fasolasuchus','Fasolasuchus','Especial','Mecânica própria','Terrestre','A domesticação usa uma sequência própria ligada ao terreno/combate; não desperdice tranquilizantes.'),
 c('Wyvern de Fogo','Fire Wyvern','Ovo','Ovo fertilizado / Leite de Wyvern','Voador','Roube o ovo do ninho e escape rápido. Leite de Wyvern ajuda a alimentar/cuidar do filhote.'),
 c('Gacha','Gacha','Passivo','Estruturas/recursos aceitos','Terrestre','Jogue o alimento/recurso no chão perto dele e deixe-o consumir. Evite outro Gacha do mesmo sexo muito próximo.'),
 c('Galimimo','Gallimimus','Nocaute','Ração Simples ou vegetais','Terrestre','É veloz e frágil: use armadilha e dardos.'),
 c('Gasbags','Gasbags','Nocaute','Ração Superior ou vegetais','Terrestre','Controle a área para ele não sair quicando/voando durante o nocaute.'),
 c('Abelha Rainha','Giant Queen Bee','Passivo','Ração Rara / alimento preferido','Voador','Destrua a colmeia, use ghillie e repelente, acompanhe a rainha e faça as alimentações passivas.'),
 c('Giganotossauro','Giganotosaurus','Nocaute','Ração Excepcional ou carne','Terrestre','Use armadilha muito resistente, muitos tranquilizantes e grande reserva de narcótico: o torpor despenca.'),
 c('Gigantopithecus','Gigantopithecus','Passivo','Ração Regular ou frutas','Terrestre','Agache e aproxime por trás. Não encoste nele entre as alimentações.'),
 c('Gigantoraptor','Gigantoraptor','Filhote','Interações com o filhote','Terrestre','Distraia a mãe e faça o minijogo/interações com o filhote até completar a domesticação.'),
 c('Glowtail','Glowtail','Passivo','Sementes de espécie Z / cogumelos','Aberração','Pet de luz: coloque o alimento preferido no último espaço e alimente passivamente.'),
 c('Grand Tortugar','Grand Tortugar','Nocaute','Ração Superior','Astraeos','Derrube em área aberta e segura; por ser grande, prepare munição e comida antes.'),
 c('Helicoprion','Helicoprion','Especial','Mecânica aquática própria','Aquático','Use a interação específica da criatura; prepare uma montaria aquática e limpe predadores próximos.'),
 c('Hesperornis','Hesperornis','Passivo','Peixe morto','Aquático','Mate peixes, carregue o corpo até ele e ofereça. Peixes maiores dão mais progresso.'),
 c('Hyaenodon','Hyaenodon','Passivo','Carinho','Terrestre','Agache, aproxime por trás e faça carinho quando aparecer a opção. Não deixe o bando entrar em combate.'),
 c('Ictiossauro','Ichthyosaurus','Passivo','Ração Simples ou carne','Aquático','Normalmente é amistoso; faça as alimentações na água e acompanhe-o entre os intervalos.'),
 c('Iguanodon','Iguanodon','Nocaute','Ração Simples ou vegetais','Terrestre','Armadilha simples resolve.'),
 c('Jerboa','Jerboa','Nocaute','Frutas','Terrestre','É muito frágil; use o mínimo de dano possível.'),
 c('Kairuku','Kairuku','Nocaute','Ração Básica ou peixe','Terrestre','Muito frágil; dardos e golpes leves são mais seguros.'),
 c('Kaprosuchus','Kaprosuchus','Nocaute','Ração Regular ou carne','Terrestre','Cuidado com o salto que desmonta o jogador.'),
 c('Karkinos','Karkinos','Especial','Ração Excepcional ou carne','Aberração','Prenda-o e acerte o corpo com projéteis de Catapulta para causar torpor. Flechas/dardos não são o método correto.'),
 c('Kentrossauro','Kentrosaurus','Nocaute','Ração Regular ou vegetais','Terrestre','Ataque de longe para evitar o dano/reflexo dos espinhos.'),
 c('Wyvern Elétrico','Lightning Wyvern','Ovo','Ovo fertilizado / Leite de Wyvern','Voador','Roube o ovo do ninho, fuja usando uma montaria rápida e incube em segurança.'),
 c('Liopleurodon','Liopleurodon','Passivo','Mel de Abelha Gigante','Aquático','É uma domesticação temporária. Alimente passivamente com mel e aproveite o bônus enquanto durar.'),
 c('Lumina','Lumina','Especial','Minijogos após enfraquecer','Voador','Reduza a vida para cerca de 20%. Ela agarrará você; complete três minijogos de memória, alvos e mergulho para concluir.'),
 c('Lymantria','Lymantria','Nocaute','Ração Regular ou vegetais','Voador','Prenda o voo ou force o pouso antes de aplicar torpor.'),
 c('Lystrosaurus','Lystrosaurus','Passivo','Flor Rara ou frutas','Terrestre','Aproxime e alimente diretamente pelo último espaço.'),
 c('Maeguana','Maeguana','Nocaute','Ração Básica ou carne nobre','Astraeos','Prenda para impedir a fuga planando; depois aplique torpor com cuidado.'),
 c('Mamute','Mammoth','Nocaute','Ração Superior ou vegetais','Terrestre','Use terreno alto ou armadilha para não ser empurrado.'),
 c('Managarmr','Managarmr','Nocaute','Ração Excepcional ou carne','Terrestre','Armadilha é quase obrigatória para conter saltos e investidas.'),
 c('Manta','Manta','Passivo','Gel de Pescador','Aquático','Aproxime com cuidado e alimente passivamente; evite encostar no corpo dela.'),
 c('Mantis','Mantis','Passivo','Chifre de Deathworm','Terrestre','Use Repelente de Insetos, mantenha distância e alimente pelo último espaço.'),
 c('Megalania','Megalania','Nocaute','Ração Extraordinária ou carne','Caverna','Cuidado com Mega Raiva. Procure-a em paredes/tetos e derrube com distância.'),
 c('Megaloceros','Megaloceros','Nocaute','Ração Simples ou vegetais','Terrestre','Armadilha simples ou bola quando aplicável facilita.'),
 c('Megalodon','Megalodon','Nocaute','Ração Superior ou carne','Aquático','Aplique torpor mantendo distância e fique atento a outros predadores.'),
 c('Megalossauro','Megalosaurus','Nocaute','Ração Superior ou carne','Aberração','Escolha um momento em que esteja menos ativo e use armadilha.'),
 c('Megatherium','Megatherium','Nocaute','Ração Superior ou vegetais','Terrestre','Evite iniciar o tame quando ele estiver com bônus de insetos.'),
 c('Mesopithecus','Mesopithecus','Passivo','Ração Básica ou frutas','Terrestre','Agache e aproxime lentamente; não esbarre nele.'),
 c('Microraptor','Microraptor','Nocaute','Ração Rara ou carne','Terrestre','É pequeno e frágil. Bola e arma fraca ajudam.'),
 c('Morellatops','Morellatops','Nocaute','Ração Simples ou vegetais','Terrestre','Isole do grupo e aplique torpor.'),
 c('Mosasaurus','Mosasaurus','Nocaute','Ração Excepcional ou carne','Aquático','Use uma armadilha submarina ou terreno submerso para limitar a movimentação.'),
 c('Moschops','Moschops','Passivo','Comida pedida na interação','Terrestre','Olhe a mensagem sobre a cabeça dele e leve exatamente o alimento solicitado; o pedido pode mudar.'),
 c('Oasisaur','Oasisaur','Especial','Mecânica própria','Terrestre','Use a mecânica exclusiva do Oasisaur; não é um tame de torpor.'),
 c('Onyc','Onyc','Passivo','Carne','Caverna','Use Repelente de Insetos e alimente sem deixar o morcego entrar em combate.'),
 c('Lontra','Otter','Passivo','Peixe morto','Aquático','Mate um peixe, carregue o corpo até a lontra e ofereça; repita.'),
 c('Oviraptor','Oviraptor','Nocaute','Ovos','Terrestre','Depois de apagar, coloque ovos no inventário. Ovos maiores rendem mais.'),
 c('Ovis','Ovis','Passivo','Bolo de Vegetais Doce','Terrestre','Uma única alimentação costuma domesticar; tenha o bolo pronto antes de se aproximar.'),
 c('Paqui','Pachy','Nocaute','Ração Simples ou vegetais','Terrestre','Evite trocar golpes de frente com as cabeçadas.'),
 c('Paquirrinossauro','Pachyrhinosaurus','Nocaute','Ração Regular / vegetais','Terrestre','ATENÇÃO: ele estava faltando pelo nome em português. Atire no CORPO, não na cabeça endurecida. O torpor cai rápido, então leve narcótico/biotoxina.'),
 c('Paraceratério','Paraceratherium','Nocaute','Ração Superior ou vegetais','Terrestre','Use bastante espaço e mantenha distância durante o nocaute.'),
 c('Parassauro','Parasaur','Nocaute','Ração Básica ou frutas','Terrestre','Bola facilita muito no início do jogo.'),
 c('Pegomastax','Pegomastax','Passivo','Mejoberry','Terrestre','Deixe frutas no último espaço e permita que ele roube repetidamente até completar.'),
 c('Pelagornis','Pelagornis','Nocaute','Ração Regular ou peixe','Voador','Bola ajuda quando ele pousa; alimente com peixe.'),
 c('Phiomia','Phiomia','Nocaute','Ração Básica ou frutas','Terrestre','Bola e poucos tranquilizantes normalmente bastam.'),
 c('Fênix','Phoenix','Especial','Dano de fogo','Voador','Durante a condição de aparição apropriada, acerte repetidamente com fontes de fogo até completar a domesticação.'),
 c('Plesiossauro','Plesiosaur','Nocaute','Ração Superior ou carne','Aquático','Só aparece em águas profundas; use armadilha submarina ou uma posição segura.'),
 c('Wyvern de Veneno','Poison Wyvern','Ovo','Ovo fertilizado / Leite de Wyvern','Voador','Roube o ovo e saia da área dos ninhos imediatamente; depois incube e crie o filhote.'),
 c('Procoptodon','Procoptodon','Nocaute','Cogumelo Raro','Terrestre','É rápido; use armadilha antes de aplicar torpor.'),
 c('Pteranodonte','Pteranodon','Nocaute','Ração Regular ou carne','Voador','Use bola quando pousar, depois tranquilizante.'),
 c('Pulmonoscorpius','Pulmonoscorpius','Nocaute','Ração Regular ou carne estragada','Terrestre','Mantenha distância do ferrão enquanto aplica torpor.'),
 c('Purlovia','Purlovia','Nocaute','Ração Regular ou carne','Terrestre','Revele-a quando estiver enterrada e só então inicie o nocaute.'),
 c('Pyromane','Pyromane','Especial','Mecânica de fogo e combate','Terrestre','Reduza a proteção flamejante e cumpra a sequência própria de montaria/combate até completar.'),
 c('Quetzal','Quetzal','Nocaute','Ração Excepcional ou carne','Voador','Como ele não pousa normalmente, use perseguição aérea e uma estratégia que permita atirar enquanto voa.'),
 c('Raptor','Raptor','Nocaute','Ração Simples ou carne','Terrestre','Bola ajuda bastante.'),
 c('Ravager','Ravager','Nocaute','Ração Superior ou carne','Aberração','Isole do bando e use armadilha.'),
 c('Rex','Rex','Nocaute','Ração Excepcional ou carne','Terrestre','Armadilha ou penhasco seguro facilita muito.'),
 c('Rhyniognatha','Rhyniognatha','Especial','Feromônio de Rhyniognatha / hospedeiro','Voador','Enfraqueça uma fêmea selvagem e use a mecânica de impregnação em uma criatura sua com o feromônio. Depois cumpra os desejos do embrião até o nascimento.'),
 c('Rock Drake','Rock Drake','Ovo','Ovo fertilizado','Aberração','Roube ovos no ninho e prepare uma rota de fuga; depois incube e crie o filhote.'),
 c('Elemental de Pedra','Rock Elemental','Especial','Ração Extraordinária ou recursos','Terrestre','Prenda-o e acerte a cabeça com canhão para causar torpor. Não use flechas/dardos como método principal.'),
 c('Roll Rat','Roll Rat','Especial','Mel / mecânica própria','Aberração','Quando ele se enterrar, jogue o recurso adequado no buraco conforme a mecânica da criatura e repita até completar.'),
 c('Tigre-dentes-de-sabre','Sabertooth','Nocaute','Ração Regular ou carne','Terrestre','Isole e use armadilha ou terreno alto.'),
 c('Sarco','Sarco','Nocaute','Ração Regular ou carne','Terrestre','Na terra é bem mais fácil de controlar.'),
 c('Shastasaurus','Shastasaurus','Especial','Mecânica aquática própria','Aquático','Domesticação avançada no oceano; use a sequência exclusiva da criatura e uma montaria aquática segura.'),
 c('Coruja da Neve','Snow Owl','Nocaute','Ração Superior ou carne','Voador','Armadilha de voo ajuda a conter a velocidade.'),
 c('Espinossauro','Spino','Nocaute','Ração Excepcional ou carne','Terrestre','Prenda ou use terreno alto; ele corre quando o torpor sobe.'),
 c('Drakeling da Primavera','Spring Drakeling','Especial','Ração Excepcional','Voador','Segure uma tocha, cumpra a tarefa indicada pelo Drakeling e alimente. Repita o ciclo até 100%.'),
 c('Estegossauro','Stegosaurus','Nocaute','Ração Regular ou vegetais','Terrestre','Mantenha distância do golpe de cauda.'),
 c('Drakeling do Verão','Summer Drakeling','Especial','Ração Excepcional','Voador','Segure uma tocha, cumpra a tarefa pedida e alimente após a atividade.'),
 c('Tapejara','Tapejara','Nocaute','Ração Superior ou carne','Voador','Ghillie e bola ajudam muito porque ele foge ao perceber o jogador.'),
 c('Terror Bird','Terror Bird','Nocaute','Ração Regular ou carne','Terrestre','É rápido; use armadilha.'),
 c('Therizinosaur','Therizinosaur','Nocaute','Ração Excepcional ou vegetais','Terrestre','Leve bastante narcótico e uma armadilha segura; ele causa muito dano.'),
 c('Dragão Espinhoso','Thorny Dragon','Nocaute','Ração Regular ou carne','Terrestre','Use armadilha e evite os espinhos à distância.'),
 c('Thylacoleo','Thylacoleo','Nocaute','Ração Extraordinária ou carne','Terrestre','Pode saltar de árvores e desmontar você. Derrube-o da árvore ou atraia para armadilha.'),
 c('Tidepup','Tidepup','Especial','Ração Regular / carne de carneiro','Aquático','Baixe a vida sua ou de um tame para menos de ~10%. Deixe o Tidepup curar o alvo; quando ele entrar no estado de descanso, alimente. Repita.'),
 c('Tricerátops','Triceratops','Nocaute','Ração Simples ou vegetais','Terrestre','Atire no corpo/lateral; a placa da cabeça reduz o efeito dos disparos frontais.'),
 c('Tusoteuthis','Tusoteuthis','Passivo','Pérolas Negras','Aquático','Deixe-o agarrar uma criatura resistente, aproxime-se do bico e entregue Pérolas Negras; saia e repita.'),
 c('Umbra','Umbra','Especial','Ração Extraordinária / costeleta de cordeiro cozida','Voador','Use Drake Claw para iniciar e complete as fases de imitação, combate sem receber dano e deslocamento. Repita os ciclos até 100%.'),
 c('Unicórnio','Unicorn','Passivo','Cenoura','Terrestre','Funciona como o Equus: alimente, monte e repita a interação sempre que tentar derrubar você.'),
 c('Velonasaur','Velonasaur','Nocaute','Ração Regular ou carne','Terrestre','Use cobertura para não tomar a rajada de espinhos durante o nocaute.'),
 c('Abutre','Vulture','Passivo','Carne estragada','Voador','Use Repelente de Insetos e alimente passivamente.'),
 c('Drakeling do Inverno','Winter Drakeling','Especial','Ração Excepcional','Voador','Segure uma tocha, cumpra a atividade solicitada e alimente. Repita até completar.'),
 c('Rinoceronte Lanoso','Woolly Rhino','Nocaute','Ração Superior ou vegetais','Terrestre','Evite ficar na linha reta de uma investida.'),
 c('Xiphactinus','Xiphactinus','Especial','Mecânica aquática própria','Aquático','Use a mecânica específica de domesticação no oceano e limpe a área de outros predadores antes de começar.'),
 c('Yutyrannus','Yutyrannus','Nocaute','Ração Excepcional ou carne','Terrestre','Separe dos Carnos, use armadilha e cuidado com o rugido de medo.'),
];

// Variantes aberrantes domesticáveis que aparecem no Astraeos.
const aberrantes=[
 ['Araneo Aberrante','Araneo','Passivo','Carne estragada','Caverna'],
 ['Arthropluera Aberrante','Arthropluera','Passivo','Caldo de Iluminação / alimento preferido','Caverna'],
 ['Carbonemys Aberrante','Carbonemys','Nocaute','Ração Regular ou vegetais','Aberração'],
 ['Carnotauro Aberrante','Carnotaurus','Nocaute','Ração Regular ou carne','Aberração'],
 ['Dimorfodonte Aberrante','Dimorphodon','Nocaute','Carne de carneiro ou carne','Aberração'],
 ['Diplodoco Aberrante','Diplodocus','Passivo','Ração Regular ou vegetais','Aberração'],
 ['Urso Gigante Aberrante','Dire Bear','Nocaute','Ração Superior ou mel','Aberração'],
 ['Dodô Aberrante','Dodo','Nocaute','Ração Básica ou frutas','Aberração'],
 ['Doedicurus Aberrante','Doedicurus','Nocaute','Ração Regular ou vegetais','Aberração'],
 ['Equus Aberrante','Equus','Passivo','Cenoura','Aberração'],
 ['Gigantoraptor Aberrante','Gigantoraptor','Filhote','Interações com o filhote','Aberração'],
 ['Iguanodon Aberrante','Iguanodon','Nocaute','Ração Simples ou vegetais','Aberração'],
 ['Lystrosaurus Aberrante','Lystrosaurus','Passivo','Flor Rara ou frutas','Aberração'],
 ['Manta Aberrante','Manta','Passivo','Gel de Pescador','Aberração'],
 ['Moschops Aberrante','Moschops','Passivo','Comida pedida na interação','Aberração'],
 ['Lontra Aberrante','Otter','Passivo','Peixe morto','Aberração'],
 ['Oviraptor Aberrante','Oviraptor','Nocaute','Ovos','Aberração'],
 ['Ovis Aberrante','Ovis','Passivo','Bolo de Vegetais Doce','Aberração'],
 ['Paraceratério Aberrante','Paraceratherium','Nocaute','Ração Superior ou vegetais','Aberração'],
 ['Parassauro Aberrante','Parasaur','Nocaute','Ração Básica ou frutas','Aberração'],
 ['Pulmonoscorpius Aberrante','Pulmonoscorpius','Nocaute','Ração Regular ou carne estragada','Aberração'],
 ['Raptor Aberrante','Raptor','Nocaute','Ração Simples ou carne','Aberração'],
 ['Sarco Aberrante','Sarco','Nocaute','Ração Regular ou carne','Aberração'],
 ['Espinossauro Aberrante','Spino','Nocaute','Ração Excepcional ou carne','Aberração'],
 ['Estegossauro Aberrante','Stegosaurus','Nocaute','Ração Regular ou vegetais','Aberração'],
 ['Tricerátops Aberrante','Triceratops','Nocaute','Ração Simples ou vegetais','Aberração']
];
aberrantes.forEach(x=>creatures.push(c(x[0],x[1],x[2],x[3],x[4],'Mesma mecânica da espécie normal, mas esta é a variante aberrante encontrada nas regiões de Aberração do Astraeos.','Aberrante')));

creatures.sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));
window.ARK_CREATURES=creatures;
